version: '3.7'

services:

  mkdocs:
    build: 
      context: .
    volumes: 
      - ${PWD}:/docs
    ports:
      - 8000:8000
    # environment:
    #   SERVICE_NAME: ${SERVICE_NAME}
    networks: 
      - network

networks:
  network:
