site_name: Guide d'exploitation
theme:
  name: material
  # extra_css:
  #   - stylesheets/extra.css
  features:
    - content.tabs.link
    - content.code.annotate
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - awesome-pages
  - render_swagger
  - mermaid2

# https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/?h=feed#google-analytics