swagger: '2.0'
info:
  title: attributes
  description: No description
  version: v1
schemes:
  - https
paths:
 
  /attributes:
    post:
      summary: create
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              id:
                type: string
              values:
                type: array
                items:
                  type: string
          required: true
      responses:
        '200':
          description: OK

  /attributes/attribute1:
    patch:
      summary: update
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              id:
                type: string
              values:
                type: array
                items:
                  type: string
          required: true
      responses:
        '200':
          description: OK

    delete:
      summary: delete
      parameters: []
      responses:
        '200':
          description: OK

  /attributes/color:
    get:
      summary: read
      parameters: []
      responses:
        '200':
          description: OK

  /attributes/list:
    get:
      summary: List
      parameters: []
      responses:
        '200':
          description: OK

