swagger: '2.0'
info:
  title: users
  description: No description
  version: v1
schemes:
  - https
paths:
  /users/{cognitoUserId}:
    get:
      summary: Get user
      parameters:
        - in: path
          name: cognitoUserId
          type: string
          required: true
      responses:
        '200':
          description: OK

    delete:
      summary: Delete user
      parameters:
        - in: path
          name: cognitoUserId
          type: string
          required: true
      responses:
        '200':
          description: OK

  /users:
    get:
      summary: Get users
      parameters: []
      responses:
        '200':
          description: OK

    post:
      summary: Create user
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              name:
                type: string
              email:
                type: string
              password:
                type: string
          required: true
      responses:
        '200':
          description: OK

  /users/{cognitoUserId}/enable:
    get:
      summary: Enable user
      parameters:
        - in: path
          name: cognitoUserId
          type: string
          required: true
      responses:
        '200':
          description: OK

  /users/{cognitoUserId}/disable:
    get:
      summary: Disable user
      parameters:
        - in: path
          name: cognitoUserId
          type: string
          required: true
      responses:
        '200':
          description: OK

  /users/{cognitoUserId}/confirm-signup:
    post:
      summary: Confirm signup user
      parameters:
        - in: path
          name: cognitoUserId
          type: string
          required: true
      responses:
        '200':
          description: OK
